In [1]:
# ____Import libraries____
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

In [2]:
# ____Load dataset____
data = pd.read_csv('data\\iris.csv')
print(data.head(5))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [6]:
# ____Preprocessing____

# Splitting the dataset in independent and dependent variables
X = data.iloc[:,:4].values
y = data['species'].values

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

# Feature Scaling to bring the variable in a single scale
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train[:5])
print('\n',y_train[:5])
print('\n',X_test[:5])
print('\n',y_test[:5])

[[-1.00251953  1.03162171 -1.40606109 -1.20517074]
 [ 2.14105929 -0.10410861  1.62428406  1.19627649]
 [-0.88161265  1.03162171 -1.34888477 -1.33858448]
 [ 0.20654925 -0.10410861  0.59511023  0.79603529]
 [ 0.56926988 -1.23983894  0.70946288  0.92944902]]

 ['setosa' 'virginica' 'setosa' 'virginica' 'virginica']

 [[ 1.05289739  0.57732958  1.10969715  1.19627649]
 [-0.03526451 -0.55840074  0.7666392   1.5965177 ]
 [-0.76070577  2.3944981  -1.29170844 -1.47199821]
 [-1.36524016  0.35018352 -1.40606109 -1.33858448]
 [-1.00251953  0.80447565 -1.23453212 -1.07175701]]

 ['virginica' 'virginica' 'setosa' 'setosa' 'setosa']


In [8]:
# ____Classify____

# Create a Gaussian Classifier
nbClassifier = GaussianNB()
nbClassifier.fit(X_train, y_train)

GaussianNB()

In [9]:
# Predicting the Test set results
y_pred = nbClassifier.predict(X_test)
print(y_pred)

['virginica' 'virginica' 'setosa' 'setosa' 'setosa' 'virginica'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'versicolor' 'virginica' 'setosa' 'virginica' 'versicolor']


In [11]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
print(y_compare)

[['virginica' 'virginica']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['versicolor' 'virginica']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['virginica' 'versicolor']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']]


In [13]:
# Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0  8  1]
 [ 0  1  9]]


In [14]:
#finding accuracy from the confusion matrix.
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9333333333333333
