In [15]:
# ____Import libraries____
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

In [16]:
# ____Load dataset____
data = pd.read_csv('data\\iris.csv')
print(data.head(5))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [17]:
# ____Preprocessing____

# Splitting the dataset in independent and dependent variables
X = data.iloc[:,:4].values
y = data['species'].values

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = None)

# Feature Scaling to bring the variable in a single scale
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train[:5])
print('\n',y_train[:5])
print('\n',X_test[:5])
print('\n',y_test[:5])

[[ 0.42715454 -1.98460517  0.41363469  0.38390278]
 [-0.8353712   2.40424041 -1.29403145 -1.43800872]
 [-0.20410833 -0.13667019  0.24286807 -0.00650683]
 [-1.08787635  0.32531355 -1.46479807 -1.30787219]
 [-0.45661348 -1.7536133   0.12902366  0.12362971]]

 ['versicolor' 'setosa' 'versicolor' 'setosa' 'versicolor']

 [[-1.08787635  1.24928105 -1.35095366 -1.30787219]
 [ 0.17464939 -1.98460517  0.69824571  0.38390278]
 [-0.96162377 -1.29162956 -0.44019838 -0.13664336]
 [-0.45661348 -1.52262143 -0.04174295 -0.2667799 ]
 [ 0.93216484 -0.13667019  0.35671248  0.25376625]]

 ['setosa' 'virginica' 'versicolor' 'versicolor' 'versicolor']


In [18]:
# ____Classify____

# Create a Gaussian Classifier
nbClassifier = GaussianNB()
nbClassifier.fit(X_train, y_train)

GaussianNB()

In [19]:
# Predicting the Test set results
y_pred = nbClassifier.predict(X_test)
print(y_pred)

['setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'setosa'
 'virginica' 'virginica' 'setosa' 'virginica' 'versicolor' 'virginica'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'versicolor'
 'setosa' 'virginica' 'versicolor' 'virginica' 'versicolor' 'setosa'
 'setosa' 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa']


In [20]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
print(y_compare)

[['setosa' 'setosa']
 ['virginica' 'versicolor']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['virginica' 'virginica']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['versicolor' 'versicolor']
 ['virginica' 'virginica']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['versicolor' 'virginica']
 ['versicolor' 'versicolor']
 ['virginica' 'virginica']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['setosa' 'setosa']
 ['versicolor' 'versicolor']
 ['setosa' 'setosa']
 ['virginica' 'virginica']
 ['setosa' 'setosa']]


In [21]:
# Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[10  0  0]
 [ 0 10  1]
 [ 0  1  8]]


In [22]:
#finding accuracy from the confusion matrix.
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9333333333333333
